### ISSUE TITLE
json format files can't imported

### ISSUE THREAD

**Issue by cyberbliss** [rundeck-plugins/git-plugin#11]
Hi

Only xml or yaml format files can be imported from git repos but not json files. Perhaps I don't understand the purpose of this plugin but as Rundeck jobs support reading json format local files to populate options values wouldn't it make sense to allow json format files to be imported as well?

Stephen

**Comment by ltamaster** [comment]
Hi @cyberbliss,

Are you talking about rundeck SCM project settings?
This repo contains the resource model plugin  (load resource files from github) and a `git clone` workflow step 

Luis

**Comment by cyberbliss** [comment]
Ah yes. Sorry, my bad!
