### ISSUE TITLE
Add ACL policy to limit who can commit and import  changes.

### ISSUE THREAD

**Issue by mlamutt** [rundeck-plugins/git-plugin#2]
I apologize if this has already been covered,  but I have not been able to find a method to edit my ACL files to restrict the "Git Import: Import Remote Changes" and "Git Export: Commit Changes to Git" to specif users, or roles.  

Is this possible?

**Comment by ltamaster** [comment]
Hi @mlamutt ,

This plugin is not related to the Git Import/Export.  You need to ask this on https://github.com/rundeck/rundeck/issues

Thanks
Luis
